# [[docs]]
#   name = "Prologue"
#   weight = 10
#   identifier = "prologue"
#   url = "/docs/prologue/"

# [[guide]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/guide/lorem/"

# [[tutorial]]
#   name = "Lorem"
#   weight = 10
#   identifier = "lorem"
#   url = "/tutorial/lorem/"

[[main]]
  name = "Accreditation"
  url = "/docs/message-from-the-university-president/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[social]]
  name = "Facebook"
  pre = '<svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-brand-facebook"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3" /></svg>'
  url = "https://www.facebook.com/bpsudinalupihan"
  weight = 10

# [[footer]]
#   name = "Privacy Policy"
#   url = "/privacy/"
#   weight = 10

[[sidebar_docs]]
  name = "Message from the University President"
  pageRef = "/docs/message-from-the-university-president/"
  weight = 10

[[sidebar_docs]]
  name = "BEED"
  pageRef = "/docs/BEED"
  weight = 20

[[sidebar_docs]]
  name = "BSED"
  pageRef = "/docs/BSED"
  weight = 30

[[sidebar_docs]]
  name = "BECED"
  pageRef = "/docs/BECED"
  weight = 40
